backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "What We Do"
      name: "what_we_do"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'what_we_do'
          name: "contents"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Icons", name: 'what_we_do_images', widget: 'image'}
            - { label: "Modal Title", name: "service_title", widget: "text" }
            - { label: "Modal Content", name: "service_content", widget: "text" }
            - { label: "Modal Image", name: "service_image", widget: "image" }
    - label: "Mantra"
      name: "mantra"
      file: "content/mantra.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Mantra'
          name: "mantras"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'hero_image', widget: 'image'}
    - label: "Mission"
      name: "mission"
      file: "content/mission.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Section Title", name: "sectionTitle", widget: "text"}
        - label: 'Mission'
          name: "missions"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'mission_image', widget: 'image'}
    - label: "Management"
      name: "management"
      file: "content/management.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Management'
          name: "managements"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'management_image', widget: 'image'}
    - label: "Products"
      name: "pro"
      file: "content/pro.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Product Content'
          name: "pros"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Logo image", name: 'logo_image', widget: 'image'}
            - { label: "Logo image", name: 'site_link', widget: 'link'}
            - { label: "Product image", name: 'product_image', widget: 'image'}       
    - label: "PostJob"
      name: "postJob"
      file: "content/postJob.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Carriers'
          name: "jobs"
          widget: list
          fields:
            - { label: "Job Title", name: "job_title", widget: "string"}
            - { label: "Job Details", name: "job_description", widget: "text"}
    - label: "Contact" 
      name: "contacts"
      file: "content/address.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "SubTitle", name: "sub_title", widget: "string"}
        - label: 'Contact Content'
          name: "address"
          widget: list
          fields:
            - { label: "Country", name: "country_name", widget: "string"}
            - { label: "Company Name", name: "company_name", widget: "text"}
            - { label: "Company State", name: "company_state", widget: "text"}
            - { label: "Company Address1", name: "company_address1", widget: "text"}
            - { label: "Company Address2", name: "company_address2", widget: "text"}
            - { label: "Contact Number", name: "contact_number", widget: "text"}
            - { label: "Contact Mail", name: "contact_mail", widget: "text"}
    - label: "Home Slides"
      name: "slide"
      file: "content/slide.md"
      fields:
        - label: 'Slides'
          name: "slides"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Sub Title", name: "sub_title", widget: "text"}
            - { label: "Slide Image", name: 'slide_image', widget: 'image'}