backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "What We Do"
      name: "what_we_do"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'what_we_do'
          name: "contents"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Icons", name: 'what_we_do_images', widget: 'image'}
    - label: "Mantra"
      name: "mantra"
      file: "content/mantra.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Mantra'
          name: "mantras"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'hero_image', widget: 'image'}
    - label: "Mission"
      name: "mission"
      file: "content/mission.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Section Title", name: "sectionTitle", widget: "text"}
        - label: 'Mission'
          name: "missions"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'mission_image', widget: 'image'}
    - label: "Management"
      name: "management"
      file: "content/management.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Management'
          name: "managements"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}
            - { label: "image", name: 'management_image', widget: 'image'}
    - label: "Products"
      name: "pro"
      file: "content/pro.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Product Content'
          name: "pros"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Logo image", name: 'logo_image', widget: 'image'}
            - { label: "Product image", name: 'product_image', widget: 'image'}       
    - label: "Services"
      name: "services"
      file: "content/service.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Service Content (left image right text)'
          name: "services"
          widget: list
          fields:
            - { label: "Service Title", name: "service_title", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Service image image", name: 'service_image', widget: 'image'}
    - label: "Services page1"
      name: "services page1"
      file: "content/service2.md"
      fields:
        - label: 'Service Content (Right image Left text)'
          name: "services"
          widget: list
          fields:
            - { label: "Service Title", name: "service_title", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "service image 2 image", name: 'service_image', widget: 'image'}
  
    - label: "PostJob"
      name: "postJob"
      file: "content/postJob.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Carriers'
          name: "jobs"
          widget: list
          fields:
            - { label: "Job Title", name: "job_title", widget: "string"}
            - { label: "Job Details", name: "job_description", widget: "text"}
