backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "What We Do"
      name: "what_we_do"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'what_we_do'
          name: "contents"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Mantra"
      name: "mantra"
      file: "content/mantra.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "image", name: 'hero_image', widget: 'image'}
        - label: 'Mantra'
          name: "mantras"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Mission"
      name: "mission"
      file: "content/mission.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Section Title", name: "sectionTitle", widget: "text"}
        - { label: "image", name: 'mission_image', widget: 'image'}
        - label: 'Mission'
          name: "missions"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Management"
      name: "management"
      file: "content/management.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "image", name: 'management_image', widget: 'image'}
        - label: 'Management'
          name: "managements"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}
    - label: "Products"
      name: "pro"
      file: "content/pro.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Logo image", name: 'logo_image', widget: 'image'}
        - { label: "Product image", name: 'product_image', widget: 'image'}
        - label: 'Product Content'
          name: "pros"
          widget: list
          fields:
            - { label: "Description", name: "description", widget: "text"}        
  
            