backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "What We Do"
      name: "what_we_do"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'what_we_do'
          name: "contents"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Mantra"
      name: "mantra"
      file: "content/mantra.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Mantra'
          name: "mantras"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}