backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "What We Do"
      name: "what_we_do"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'what_we_do'
          name: "contents"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "Mantra"
      name: "mantra"
      file: "content/mantra.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "image", name: 'hero_image', widget: 'image'}
        - label: 'Mantra'
          name: "mantras"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "text"}
        - { label: "image", name: 'mission_image', widget: 'image'}
        - label: 'About'
          name: "aboutUs"
          widget: aboutList
          fields:
            - { label: "Title", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}  
            - { label: "image", name: 'mission_image', widget: 'image'}      
        - label: 'About'
          name: "management"
          widget: managementDetails
          fields:
            - { label: "Description", name: "description", widget: "text"}  
            - { label: "image", name: 'mange_image', widget: 'image'}
            